<?php

namespace App\Models;

use Cubes\Nestpay\Laravel\PaymentModel as Model;

class NestpayPayment extends Model
{
    /*protected $table = 'nestpay_payments';

    protected $fillable = [
		'processed',
		'oid',
		'trantype',
		'currency',
		'amount',
		'Response',
		'AuthCode',
		'ProcReturnCode',
		'TransId',
		'ErrMsg',
		'mdStatus',
		'email',
		'tel',
		'description',
		'BillToCompany',
		'BillToName',
		'BillToStreet1',
		'BillToStreet2',
		'BillToCity',
		'BillToStateProv',
		'BillToPostalCode',
		'BillToCountry',
		'ShipToCompany',
		'ShipToName',
		'ShipToStreet1',
		'ShipToStreet2',
		'ShipToCity',
		'ShipToStateProv',
		'ShipToPostalCode',
		'ShipToCountry',
		'DimCriteria1',
		'DimCriteria2',
		'DimCriteria3',
		'DimCriteria4',
		'DimCriteria5',
		'DimCriteria6',
		'DimCriteria7',
		'DimCriteria8',
		'DimCriteria9',
		'DimCriteria10',
		'instalment',
		'INVOICENUMBER',
		'storetype',
		'lang',
		'xid',
		'HostRefNum',
		'clientIp',
		'ReturnOid',
		'MaskedPan',
		'rnd',
		'merchantID',
		'txstatus',
		'iReqCode',
		'iReqDetail',
		'vendorCode',
		'PAResSyntaxOK',
		'PAResVerified',
		'eci',
		'cavv',
		'cavvAlgorthm',
		'md',
		'Version',
		'SID',
		'mdErrorMsg',
		'TRANID',
		'clientid',
		'EXTRA_TRXDATE',
		'comments',
		
		'ACQBIN',
		'acqStan',
		'cavvAlgorithm',
		'digest',
		'dsId',
		'Ecom_Payment_Card_ExpDate_Month',
		'Ecom_Payment_Card_ExpDate_Year',
		'EXTRA_CARDBRAND',
		'EXTRA_CARDISSUER',
		'EXTRA_INVOICENUMBER',
		'failUrl',
		'HASH',
		'hashAlgorithm',
		'HASHPARAMS',
		'HASHPARAMSVAL',
		'okurl',
		'refreshtime',
		'SettleId',
    ];*/
}